/** IPC event names between injected scripts and the host. */

// Inject -> host
export const INJECTOR_READY = 'injector-ready'
export const CHECK_LOGIN_STATUS = 'checkLoginStatus'
export const SYNC_PROFILE = 'sync-profile'
export const GET_USER_PHONE_NUMBER = 'get-user-phone-number'
export const CHAT_CONTACT_RES = 'chat-contact-res'
export const GET_UNREAD = 'getUnread'
export const UPLOAD_MSG = 'upload-msg'
export const GET_NEW_MESSAGE = 'get-new-message'
export const GET_WID_AVATAR = 'get-wid-avatar'
export const CHINESE_DETECTION_PROMPT = 'chineseDetectionPrompt'
export const LOGOUT_OK = 'logout-ok'
export const SEND_EXTRA_LENGTH = 'sendExtraLength'
export const OPEN_CHAT_FAIL = 'open-chat-fail'
export const FB_MESSENGER_USER_INFO = 'fb-messenger-user-info'
export const OPERATE_LOGS = 'operateLogs'
export const UPDATE_UNREAD_COUNT = 'update-unread-count'
export const SEND_PREVENT = 'send-prevent'
export const ERROR_MSG_TIPS = 'error-msg-tips'
export const REPORT_ERROR = 'report-error'
export const GET_ACTIVE_CHAT = 'get-active-chat'
export const TRANSLATION_CONTAINS_CHINESE = 'translation-contains-chinese'
export const TRANSLATE_API = 'translate-api'
export const TRANSLATE_VOICE_API = 'translate-voice-api'
export const TRANSLATE_MEDIA_API = 'translate-media-api'
export const TRANSLATE_MEDIA_CANCEL = 'translate-media-cancel'
export const SET_CLIPBOARD = 'set-clipboard'
export const GET_NAME_MAPS = 'get-name-maps'

// Host -> inject
export const SET_INVITE_CODE = 'set-inviteCode'
export const CHANGE_SESSION = 'change-session'
export const CHANGE_WEBVIEW = 'change-webview'
export const GET_CHAT_CONTACT = 'get-chat-contact'
export const SWITCH_THEME = 'switch-whatsapp-theme'
export const LOGOUT = 'whatsapp-logout'
export const NO_TRANSLATE_CONFIRM = 'no-translate-confirm'
export const NO_TRANSLATE_CANCEL = 'no-translate-cancel'
export const SEND_QUICK_REPLY = 'send-quick-reply'
export const SEND_GROUP_MESSAGE = 'send-group-message'
export const OPEN_CHAT = 'open-chat'
export const LANG_SETTING_CHANGE = 'update-lang-setting'
export const VOICE_SETTING_CHANGE = 'update-voice-setting'

export const WEBVIEW_READY = 'webview-ready'
export const WEBVIEW_READY_TIMEOUT = 'webview-ready-timeout'
export const AUTH_STATUS_CHANGE = 'auth-status-change'
